// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="Program.cs" company="Zealag">
//    Copyright © Zealag 2016. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Zealag
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
